### ISSUE TITLE
Integration stopped working after update Home Assistant to 2022.8.0

### ISSUE THREAD

**Issue by arboeh** [syssi/homeassistant-goecharger-mqtt#46]
The integration stopped working after update to Home Assistant to 2022.8.0 yesterday. I had no problems before updating.
I got the following error message in the log then:

```
Logger: homeassistant.config_entries
Source: [config_entries.py:796](http://config_entries.py:796/)
First occurred: 20:47:15 (3 occurrences)
Last logged: 20:47:52

Error occurred loading configuration flow for integration goecharger_mqtt: cannot import name 'MqttServiceInfo' from 'homeassistant.components.mqtt' (/usr/src/homeassistant/homeassistant/components/mqtt/__init__.py)
```

I tried to reinstall the integration and now I get the following message:

![2022-08-04 06_20_29-Window](https://user-images.githubusercontent.com/12322114/182762873-18d55edd-e97b-484d-b38d-d0a73e38b628.png)

**Comment by ju55i** [comment]
I think the import line should now be "from homeassistant.helpers.service_info.mqtt import MqttServiceInfo"

**Comment by syssi** [comment]
The PR is merged and a new release is available. Please give it a try!

**Comment by arboeh** [comment]
Wow! Thanks for super fast fix...
